[package]
name = "pontus"
version = "1.0.1"
description = "Litellm Admin Desktop App"
authors = ["NUL4i"]
edition = "2021"

[lib]
name = "pontus_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["devtools"] }
tauri-plugin-opener = "2"
tauri-plugin-store = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.12", features = ["json", "blocking"] }
lettre = { version = "0.11", features = ["builder", "smtp-transport", "tokio1-native-tls"] }
tokio = { version = "1", features = ["full"] }

